version: '3'

services:
  test_db:
    image: postgres
    container_name: test_db_2
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: lyle
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lyle
    ports:
      - 5437:5432

  dev_db:
    image: postgres
    container_name: dev_db_2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: lyle
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lyle
    ports:
      - 5438:5432

volumes:
  postgres_data:
